name: Pipeline

on: [push]

env:
  BUILD_TYPE: Release
  NOMBRE_RELEASE: chil-plataforma-esp

jobs:
  construccion:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Configurar python
      uses: actions/setup-python@v2

    - name: Instala PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - name: Construye
      run: |
        platformio run -e esp32dev

  versionado:
    runs-on: ubuntu-latest
    needs: construccion
    env:
      MENSAJE_COMMIT: ${{ github.event.head_commit.message }}
    if: "!startsWith(github.event.head_commit.message, '[VERSION]')"
    steps:
      - uses: actions/checkout@v2
      - name: Generar version
        id: genera_version
        working-directory: ${{github.workspace}}
        shell: bash
        run: |
          chmod +x ./scripts/versionar.sh ./scripts/liberar-version.sh
          ./scripts/liberar-version.sh "${MENSAJE_COMMIT}"
          echo "::set-output name=version::$(cat version)"
    outputs:
      version: ${{ steps.genera_version.outputs.version }}

  publicacion:
    runs-on: ubuntu-latest
    needs: versionado
    steps:
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Configurar python
        uses: actions/setup-python@v2

      - name: Cambia a master
        uses: actions/checkout@v2
        with:
          ref: 'master'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Genera comprimido para platformio
        env:
          PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}
          version: ${{ needs.versionado.outputs.version }}
        run: |
          echo "version $version"
          chmod +x ./scripts/generar-paquete-platformio.sh && ./scripts/generar-paquete-platformio.sh

      - name: Crea borrador de publicación
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: crear_publicacion
        uses: actions/create-release@v1
        with:
          tag_name: ${{ needs.versionado.outputs.version }}
          release_name: ${{ needs.versionado.outputs.version }}
          draft: true
          prerelease: false

      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.crear_publicacion.outputs.upload_url }}
          asset_path: ./${NOMBRE_RELEASE}-${{ needs.versionado.outputs.version }}.tar.gz
          asset_name: ${NOMBRE_RELEASE}-${{ needs.versionado.outputs.version }}.tar.gz
          asset_content_type: application/gzip

      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.crear_publicacion.outputs.id }}